-- User Table
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastSeen" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "isOnline" BOOLEAN NOT NULL DEFAULT false;

-- Admin Table
ALTER TABLE "Admin" ADD COLUMN IF NOT EXISTS "lastSeen" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP;

-- Application Table
ALTER TABLE "Application" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "Application" ADD COLUMN IF NOT EXISTS "interviewDate" TEXT;
ALTER TABLE "Application" ADD COLUMN IF NOT EXISTS "interviewTime" TEXT;

-- Message Table (if any of these were missed)
ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "originalMessage" TEXT;
ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "fileUrl" TEXT;
ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "fileType" TEXT;
ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "fileName" TEXT;
ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "isDeleted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'sent';
ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "seenAt" TIMESTAMP(3);
ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);

-- Startup Table (in case any were missed)
ALTER TABLE "Startup" ADD COLUMN IF NOT EXISTS "registrationId" TEXT;
ALTER TABLE "Startup" ADD COLUMN IF NOT EXISTS "linkedinUrl" TEXT;
ALTER TABLE "Startup" ADD COLUMN IF NOT EXISTS "twitterUrl" TEXT;
